services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ioteste-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped
    networks:
      - ioteste-net

  subscriber:
    build:
      context: ..
      dockerfile: Dockerfile
      target: subscriber
    container_name: ioteste-subscriber
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "+/status/#"
      MQTT_CLIENT_ID: ioteste-subscriber
      ROOMS_FILE: /data/rooms.json
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - ./data/rooms.json:/data/rooms.json:ro
    restart: unless-stopped
    networks:
      - ioteste-net

  generator:
    build:
      context: ..
      dockerfile: Dockerfile
      target: generator
    container_name: ioteste-generator
    depends_on:
      - mosquitto
      - subscriber
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: ioteste-generator
      GENERATOR_INTERVAL_MS: 10000
    restart: unless-stopped
    networks:
      - ioteste-net

  api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: api
    container_name: ioteste-api
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-ioteste}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ioteste-net

  #mongodb:
    #image: mongo:8
    #container_name: ioteste-mongodb
      #ports:
      #- "27017:27017"
      #volumes:
      #- mongodb-data:/data/db
    #restart: unless-stopped
      #networks:
      #- ioteste-net


networks:
  ioteste-net:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log:
  #mongodb-data: