spring.application.name=ioteste-api

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:ioteste}
switch.stub.url=${SWITCH_STUB_URL:http://localhost:8081}

server.port=8080

ioteste.api.key=${IOTESTE_API_KEY}